/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './components/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './plugins/**/*.{js,ts,jsx,tsx}',
  ],
  daisyui: {
    themes: [
      {
        cmyk: {
          ...require('daisyui/src/theming/themes')['cmyk'],
          primary: "#0230FF",
          secondary: "#494454",
          accent: "#AEA8BA",
          neutral: "#FF724C",
          info: "#58FBDA",
          success: "#00AD76",
          warning: "#F9F871",
          error: "#FF0019",
          black: '#000000',
          white: '#ffffff',
          icewhite: '#ebebeb',
          grey: '#5d5d5d',
          lightblue: '#9daaf2',
          darkblue: '#1a2238',
          blackblue: '#0c1220',
          orange: '#ff6a3d',
        },
        night: {
          ...require('daisyui/src/theming/themes')['night'],
          primary: "#0F111A",
          secondary: "#302F3D",
          accent: "#574F62",
          neutral: "#00A189",
          info: "#20546C",
          success: "#5E513B",
          warning: "#E7BAD2",
          error: "#513437",
          black: '#000000',
          white: '#ffffff',
          icewhite: '#ebebeb',
          grey: '#5d5d5d',
          lightblue: '#9daaf2',
          darkblue: '#1a2238',
          blackblue: '#0c1220',
          orange: '#ff6a3d',
        },
      },
    ],
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
}
